# Generated by Django 6.1.1 on 2026-10-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
